# Copyright 2018 The YARL-Project, All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from yarl import backend
from yarl.graphs import GraphBuilder
from yarl.graphs.graph_executor import GraphExecutor

from .test_util import recursive_assert_almost_equal, root_logger


class ComponentTest(object):
    """
    A simple (and limited) Model-wrapper to test a single component in an easy, straightforward way.
    """
    def __init__(self, component, input_spaces=None, seed=10, logging_level=None):
        """
        Args:
            component (Component): The Component to be tested (may contain sub-components).
            input_spaces (Optional[dict]): Dict with component's in-Socket names as keys and Space objects as values.
                Describes the input Spaces for the component. None if the Component to be tested has no
                in-Sockets.
            seed (Optional[int]): The seed to use for random-seeding the Model object.
                If None, do not seed the Graph (things may behave non-deterministically).
            logging_level (Optional[int]): When provided, sets YARL's root_logger's logging level to this value.
        """
        self.seed = seed
        if logging_level is not None:
            root_logger.setLevel(logging_level)

        # Create our Model.
        self.graph_builder = GraphBuilder()

        # Add the component to test and expose all its Sockets to the core component of our Model.
        self.core = self.graph_builder.get_default_model()
        self.core.add_component(component, connections=True)

        # Add the input-spaces to the in-Sockets.
        for in_socket in self.core.input_sockets:
            name = in_socket.name
            assert name in input_spaces, "ERROR: C'tor parameter `input_spaces` for {} does not contain " \
                                         "Space information for in-Socket '{}'!".format(type(self).__name__, name)
            self.core.connect(input_spaces[name], name)

        # Build the model.
        self.graph_executor = GraphExecutor.from_spec(
            backend,
            graph_builder=self.graph_builder,
            execution_spec=dict(seed=self.seed)
        )
        self.graph_executor.build()

    def test(self, out_socket_names, inputs=None, expected_outputs=None, decimals=7, fn_test=None):
        """
        Does one test pass through the component to test.

        Args:
            out_socket_names (Union[str,dict,list]): The names of the out-Sockets to trigger.
            inputs (Optional[dict,np.ndarray]): Dict with the in-Socket names as keys and the data (np.arrays,
                dicts, tuples) as values. Alternatively - if there is only one possible in-Socket - can pass in
                the data directly. None if no in-Socket is needed.
            expected_outputs (Optional[any]): The expected output generated by the out-Socket
                given by `out_socket_names`. If None, no checks will be done on the output.
            decimals (Optional[int]): The number of digits after the floating point up to which to compare actual
                outputs and expected values.
            fn_test (Optional[callable]): Test function to call with (self, outs) as parameters.

        Returns:
            any: Outputs of tested operations on the specified out-Sockets.
        """
        # Get the outs ..
        outs = self.graph_executor.execute(sockets=out_socket_names, inputs=inputs)

        #  Optionally do test asserts here.
        if expected_outputs is not None:
            self.assert_equal(outs, expected_outputs, decimals=decimals)

        if callable(fn_test):
            fn_test(self, outs)

        return outs

    def variable_test(self, variables, expected_values):
        """
        TODO: documentation and implementation

        Args:
            variables ():
            expected_values ():

        Returns:

        """
        pass

    def get_variable_values(self, *variables):
        """
        Executes a session to retrieve the values of the provided variables.

        Args:
            variables (Union[variable,List[variable]]): Variable objects whose values to retrieve from the graph.

        Returns:
            any: Values of the variables provided.
        """
        return self.graph_executor.read_variable_values(variables)

    @staticmethod
    def assert_equal(outs, expected_outputs, decimals=7):
        """
        Convenience wrapper: See implementation of `recursive_assert_almost_equal` for details.
        """
        recursive_assert_almost_equal(outs, expected_outputs, decimals=decimals)
